ja:
  activerecord:
    errors:
      models:
        account:
          attributes:
            username:
              invalid: アルファベット・数値・アンダースコア（_）で入力してください
        status:
          attributes:
            reblog:
              taken: のブーストはすでに存在します
